### ISSUE TITLE
Seperate products with a linebreak rather than a comma

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#101]
![image](https://user-images.githubusercontent.com/53372693/103140696-11366080-46ea-11eb-96bd-95888fcd9411.png)
probably an issue only for non-editors+, but they're especially hard to read through when you've got a bunch of them. Seeing them seperately would make everything much easier to proofread when you've got a bunch of them, and would look like how they normally would if it was all linked

**Comment by Illidanz** [comment]
I think this is a good idea, but we can't really apply this retroactively since a lot of albums have unlinked products and a lot of products have commas in their name.

We will probably move away from comma separated fields like we did with artists eventually.

**Comment by vgmcal** [comment]
@Illidanz I guess it's not common knowledge, but you can line separate the products as long as you have a comma on each line:

![image](https://user-images.githubusercontent.com/74626685/103256044-57412d80-4951-11eb-8277-03643fe94723.png)

I've often done this with larger product lists and it works for me.
