### ISSUE TITLE
Check variations field when linking artists

### ISSUE THREAD

**Issue by vgmcal** [vgmdb/tracker#115]
The variations field is not checked under the current system. This means a lot of typos and minor name variations are not getting linked to artist pages.

For example, this output will not result in a match:
![image](https://user-images.githubusercontent.com/74626685/103588024-00d27280-4eae-11eb-8495-5eee3cdc4f92.png)

Despite both names matching the artist page:
![image](https://user-images.githubusercontent.com/74626685/103588042-09c34400-4eae-11eb-8eb6-8a7b76dcd68a.png)

**Comment by vgmcal** [comment]
It seems to be a bug where kanji variations are ignored when matching. English variations work just fine.

**Comment by Illidanz** [comment]
Note that this is only fixed for the specific issue (variation in the Original field), matching variations with the Alias field would require reworking the variations system.
