### ISSUE TITLE
[Drafts] Assign ID directly through mass add

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#120]
Some names don't get picked up through mass add due to being a variation.

See "俺-1" here: 
![image](https://user-images.githubusercontent.com/53372693/103747032-4d2ec700-5002-11eb-9072-867e2bae1a58.png)

I can understand why variations shouldn't be automatically assigned to certain artists, but maybe a simpler fix for that one would be a way to directly assign a certain ID to a certain artists through a certain way tag them?

![image](https://user-images.githubusercontent.com/53372693/103747205-967f1680-5002-11eb-8313-d34eb75b2fce.png)
Something in those lines, if that's even possible at all

**Comment by Illidanz** [comment]
This is not possible to do directly from the parser since the ID can only be assigned in a later step.

That being said, #115 should help with this issue.
