### ISSUE TITLE
Add internal linking to products

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#122]
`source: [product=29]Touhou Kaeidzuka ~ Phantasmagoria of Flower View.[/product]`

**Comment by Illidanz** [comment]
I don't think this is a good way to use notes, since the products are already linked and there are more nuances (like single or multiple releases). This should probably be solved with track credits (see #26) where a single track can be linked to a product.

**Comment by Fivda** [comment]
Oh interesting, thought ind track credits would be reserved for artists only
