### ISSUE TITLE
Keep History traces of Scans modifications

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#143]
Almost every elements of an album's informations are kept in the history. Almost everything except the scans names modifications or deletions. There should be a way to check if a scan has been renamed or deleted in the past: not necessarily keeping the picture, but preserving the changes throughout the time may sound important to see what has changed, because there's no way to tell if a scan has been renamed aside from memory alone, which is far from practical

**Comment by vgmcal** [comment]
Please see #52
