### ISSUE TITLE
[Artist Pages] "Other Spelling" displays nothing in the brackets if the spelling is in latin

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#197]
![image](https://user-images.githubusercontent.com/53372693/108611719-7ef8c300-73e1-11eb-961c-f36694fb381a.png)

**Comment by vgmcal** [comment]
I wonder if there's a better, less confusing way to display these types of names too. Like displaying "(intentionally romanized)" instead of just removing the brackets.

I'll also plug #128 while I'm here.
