### ISSUE TITLE
Add additional info to div id hsId6 in the Covers Gallery tab

### ISSUE THREAD

**Issue by jsutan** [vgmdb/tracker#212]
When viewing a cover in the Covers side pane in Gallery tab, please add some additional information to the bottom info tab (div id=hsId6). Would like to see:

- User that submitted the image (this is already in the child div but commented out...?)
- Title of the cover (i.e., "Front", "pg. 6-7", etc.)

**Comment by Illidanz** [comment]
I believe the commented out submitter is intentional, although I don't quite remember the reasoning. @Kenneth-T-Moore probably does.
