### ISSUE TITLE
Indicator for total referenced works

### ISSUE THREAD

**Issue by NicolaasHamman** [vgmdb/tracker#220]
Perhaps something like this.
![image](https://user-images.githubusercontent.com/76005677/111122721-154e7d80-8577-11eb-8183-b948d1cdd030.png)

**Comment by vgmcal** [comment]
How about this:
![image](https://user-images.githubusercontent.com/74626685/111210097-d29e9c80-859a-11eb-96fc-ba1d90b0482e.png)
