### ISSUE TITLE
The number of credits returned on the artist linking page should be for that specific alias

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#23]
Example: Currently [Tomoyuki Hamada](https://vgmdb.net/artist/757) is returned as the top result when linking TOMO as a lyricist, even though he has only 1 credit as TOMO.

I guess it will become less problematic with the new method of separating out aliases into actual alias entries, but probably still good to have.

**Comment by Illidanz** [comment]
Closing this since it shouldn't be an issue with the way we're splitting aliases now, and matching the alias for counting the work credit would break variations.
