### ISSUE TITLE
Settings button doesn't appear on iOS / Chrome

### ISSUE THREAD

**Issue by jsutan** [vgmdb/tracker#235]
The settings button doesn't show up on iOS / Chrome.

User agent string: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1

![C3568152-2C94-47DE-8F77-CA0338933592](https://user-images.githubusercontent.com/6308057/113360724-5638e700-9318-11eb-9a2f-9641cd1abf53.png)

**Comment by Illidanz** [comment]
"Fixed" by removing the not-very-useful users button.
