### ISSUE TITLE
Add new organization types

### ISSUE THREAD

**Issue by vgmcal** [vgmdb/tracker#241]
Music Production Company
Artist Management Company
Design Company
Animation Studio
Musical Equipment Company
Manufacturer
Split "Retailer / Distributor" into two (will require manually changing the existing ones)

**Comment by vgmcal** [comment]
Related: #11

**Comment by nstz0** [comment]
Another one to add is "Instrument Company" for stuff like https://vgmdb.net/artist/38765

Edit: Nevermind, cal already included this as Musical Equipment Company.
