### ISSUE TITLE
Niche feature: full TOC entries for discs

### ISSUE THREAD

**Issue by ToadKing** [vgmdb/tracker#253]
Right now we have the ability to add FreeDB IDs to discs. If we allowed inputting the actual full disc TOC instead we could then use that to calculate FreeDB IDs for the FreeDB server and allow for users to use the full TOC for lookups in other disc databases. (For example: CUETools Database/CTDB and MusicBrainz DiscIDs). It could also be used for automatically filling in tracklist times and avoiding differences in times that arise from different rounding methods for track times.

One possible format is the CDTOC tag that dBpoweramp and some other CD rippers use: https://forum.dbpoweramp.com/showthread.php?16705-FLAC-amp-Ogg-Vorbis-Storage-of-CDTOC It also has the advantage of also handling data tracks for mixed media CDs.

**Comment by Illidanz** [comment]
This will be added with #22
