### ISSUE TITLE
Wrong entry displayed in Recent Updates when rejecting tracklist edits in some cases

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#266]
![image](https://user-images.githubusercontent.com/74592463/119207807-6dce5980-ba97-11eb-9af0-3232c15b002f.png)
The edit that was rejected was https://vgmdb.net/db/albums-history.php?id=108998&tab=tracklist
The entry which appeared in Recent Updates was https://vgmdb.net/album/4334

**Comment by Illidanz** [comment]
The fix is not retroactive but going forward it shouldn't happen anymore.
