### ISSUE TITLE
Remove the legacy assign artists form

### ISSUE THREAD

**Issue by vgmcal** [vgmdb/tracker#269]
![image](https://user-images.githubusercontent.com/74626685/119268426-8b471480-bbb8-11eb-8576-9c760432660f.png)

Since adding the new mass add form, this one no longer has a good purpose.

New users are still using this old form without even trying the new one, probably because the old one is at the top of the page and is the first thing that they see. Removing this will force users to learn the new system, which is better and more efficient.

No functionality would be lost. You can still add single artists through the mass add form.

**Comment by Elena0413** [comment]
There needs to remain a way to check the roles, to see if an obscure one is in the system without having to traverse to another page entirely.

**Comment by vgmcal** [comment]
> There needs to remain a way to check the roles, to see if an obscure one is in the system without having to traverse to another page entirely.

I think we could add a dropdown menu next to the mass add form that lets you search for roles and insert them.
