### ISSUE TITLE
Update database to utf8mb4 

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#292]
Currently the character 𠮷 cannot be entered into the database and had to be approximated as 吉.
![image](https://user-images.githubusercontent.com/74592463/124379357-6ca36580-dcae-11eb-916f-967ae7f38670.png)

**Comment by Illidanz** [comment]
Before this can be done, the entries in the "Unassigned Artists" staff page need to be cleaned up, since we need to get rid of the old fields.
