### ISSUE TITLE
Sorting Catalog # by name doesn't work properly with multi-digit numbers

### ISSUE THREAD

**Issue by Elena0413** [vgmdb/tracker#300]
It only accounts for the first number (e.g. "1004" is considered a lower number than "103", "33" a higher number than "117", etc)
![image](https://user-images.githubusercontent.com/14397824/126230727-6af52b8e-63ec-493b-a706-caea32ee5945.png)

**Comment by Illidanz** [comment]
The sorting is done on the database side, so it relies on the catalog being properly formatted (with leading zeros).

Unfortunately it doesn't work in all cases like this, but we can't really easily fix in all pages due to some of them being paginated.
