### ISSUE TITLE
Update URL in edit rejection message

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#331]
Edit rejection PMs contain the following message: "If you feel the rejection is in error, please post further information or evidence in the appropriate discussion thread."

This currently links to album discussion thread. Since there are now specific discussions for particular edits, it should link there instead.

**Comment by nstz0** [comment]
Alternatively if #71 is implemented this will not be necessary.

**Comment by Illidanz** [comment]
Closing this since it's not relevant anymore after implementing #71.
