### ISSUE TITLE
Some albums appear to be missing from the calendar

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#334]
![image](https://user-images.githubusercontent.com/74592463/128646084-37d0f818-0272-4ed4-8a5b-161a38efa862.png)
![image](https://user-images.githubusercontent.com/74592463/128646091-832f50e1-2022-4d85-8ba8-a5e7e71e421b.png)
Only the 2 reprints appear in the calendar.

**Comment by nstz0** [comment]
Not limited to delayed albums:
![image](https://user-images.githubusercontent.com/74592463/128733922-e138af15-124b-461f-9f46-38b11ed01ecc.png)
This single has three editions but only the reprint appears in the calendar.

**Comment by Illidanz** [comment]
I believe delayed albums are not supposed to appear in the calendar, but might not be handled correctly for reprints.

Will take a look at the other issue as well.
