### ISSUE TITLE
CDDB - method to link CDDB matches to VGMdb album IDs

### ISSUE THREAD

**Issue by jprjr** [vgmdb/tracker#370]
Hi there - it seems like when searching using CDDB, matches have unique "genre" values, is that correct?

Is there a way to take that genre value, and extract/transform the returned value into the VGMdb album ID?

Example, [this query](http://vgmdb.net/cddb?cmd=cddb+query+930afa0c+12+0+22827+44407+64872+85725+107922+126150+144205+144872+145770+150117+183455+2810&hello=jprjr&proto=6) gives the response:

```
200 Soundtrack1967 930afa0c [MJCA-00012] Sonic R
```

In this case, the VGMdb album ID number is 1646. Is there some way to convert that `Soundtrack1967` value back into `1646`? Or is that `Soundtrack1967` value generated some other way?

Alternatively, maybe the EXTD field in the ["cddb read"](http://vgmdb.net/cddb?cmd=cddb+read+Soundtrack1967+930afa0c&hello=jprjr&proto=6) response could include the VGMdb album ID? Something like EXTD= album/1646

If there's concern about existing clients not understanding the EXTD field, it could probably be placed in a comment field.

**Comment by Illidanz** [comment]
The ID in the response is the media ID instead of the album ID, as that's needed to return the correct disc for multi-disc albums.

That being said there's no way to get to the album ID from the read, so I think we can get that EXTD field added.
