### ISSUE TITLE
Queue status header and buttons for the top of album pages.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [vgmdb/tracker#371]
All users see:

- Header: "This album is pending in the queue." for a new album that is pending.
- Header: "This album has pending edits." for an album with pending edits in the album data or the media data.
- Header: "This album has pending tracklist changes." for an album with new tracklist or tracklist edits.
- Header: "This album has pending scans." for an album with new scans or scan metadata changes.
- Header: "This album has pending links." for an album with new links.

Staff only sees:
- The "album pending" header also contains an accept and reject button.
- Accepting the album accepts all pending edits on the page. (Identical behavior to modq)
- Rejecting the album rejects the new album entry, and clears the remaining edits (Identical behavior to modq)

Open Questions
- What should it look like?
- Should we adept new term for "moderation queue"?
- If we add other statuses (hold), does the text change here?

**Comment by Illidanz** [comment]
Mockup by cal for the staff version.
![image](https://user-images.githubusercontent.com/7954143/149479563-0ff64880-1236-495e-8b73-fe303cd5a404.png)
