### ISSUE TITLE
Add "pencil" icon to the remaining places that are missing on the album page.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [vgmdb/tracker#372]
Add the "pencil" icon to the missing places. These are:

- By tracklist name for new tracklists.
- Each track when a track is edited.
- By scan if scan is new.
- By link if link is new.
- By "Notes" if the notes have been edited.
-  Classification and Catalog Number
-  Org field is currently broken.
-  All fields related to Media.
- (Any that i have missed?)

**Comment by nstz0** [comment]
> (Any that i have missed?)

The icon no longer works for the organization field since the display change. And should probably add them to the artist pages too.

**Comment by Kenneth-T-Moore** [comment]
Thanks @nstz0 .  I should make a thread for the artist pages too.

**Comment by Illidanz** [comment]
Closing this since #371 will be implemented instead.
