### ISSUE TITLE
Prevent undocumented changes of track lengths

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#405]
Currently it's possible to change the track lengths of an album by submitting a new tracklist with Default flag applied. These changes are not recorded in the edit history.

It is also not possible to know whether a newly-submitted tracklist has changed the track times when moderating an album. There should at least be a warning for the moderator if the newly-submitted tracklist is making changes to the track times.

And it's been a while since I last checked this so I'm not sure on this point but I don't think even rejecting the new tracklist brings back the old track times.

**Comment by nstz0** [comment]
> And it's been a while since I last checked this so I'm not sure on this point but I don't think even rejecting the new tracklist brings back the old track times.

Can confirm that rejecting a new default tracklist doesn't get rid of changes made to track times. Had to be reverted manually: https://vgmdb.net/db/albums-history.php?id=114002&tab=tracklist

**Comment by Illidanz** [comment]
Dependant on the new database structure for #22 and #26.
