### ISSUE TITLE
Maximum Pending Drafts Should Account For Additions By Others

### ISSUE THREAD

**Issue by Elena0413** [vgmdb/tracker#407]
The "Maximum number of pending albums without an artist draft (3) exceeded" page currently includes things which have credits applied but not by the submitter. Obviously, a user can't add a draft to something which already has complete credits:
![image](https://user-images.githubusercontent.com/14397824/135696943-d1817041-7404-4170-a82e-de529cf1a5e0.png)
![image](https://user-images.githubusercontent.com/14397824/135696950-8c2a1fd4-f1e4-4fc7-a8ea-c4094178d582.png)

**Comment by vgmcal** [comment]
To be clear: These albums were submitted as reprints and were then changed to non-reprints by staff (myself). At the time, I also copied over the credits from the former parent album. This resulted in 3 entries with credits already applied and no need for a draft.

**Comment by Illidanz** [comment]
This is working as intended since the albums in this case needed to be approved after being unstitched. The use case for the limit is meant to last until the albums are approved, even if some other user fixes the album for the submitter.
