### ISSUE TITLE
Titles double-escaped on release-history.php

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#411]
https://vgmdb.net/db/release-history.php?id=13257
In two locations:
`<title>Edit History - Isekai Izakaya &amp;quot;Nobu&amp;quot; - VGMdb</title>`
`<span>Isekai Izakaya &amp;quot;Nobu&amp;quot;</span>`

**Comment by Illidanz** [comment]
Also fixed in product-history.
