### ISSUE TITLE
When reference links are formed for url's that end in a parentheses, the closing parenthesis is cut off.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [vgmdb/tracker#415]
See here:

https://vgmdb.net/db/albums-history.php?id=115475

**Comment by nstz0** [comment]
I pointed this out to Illidan before, but it seems like vBulletin actually does this on purpose to avoid including the parentheses when urls are posted like this (https://vgmdb.net/db/albums-history.php?id=115475).

**Comment by Illidanz** [comment]
That's correct. This is the regex vbulletin uses if anyone wants to try tweaking it: https://regex101.com/r/XUInxC/1

**Comment by Illidanz** [comment]
A new regex was provided by nstz, please reopen this if any issue comes up.
The fix is not retroactive.
