### ISSUE TITLE
New price type for digital purchases that are gated behind an additional paid subscription.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [vgmdb/tracker#470]
New price type "Subscription Required". This is for albums (mostly in China) that require a paid subscription to have the opportunity to purchase them. The price will display on the album page as "2.8 RMB (requires paid subscription)".

Note that the difference between this an streaming services like spotify is that you have paid for the rights to keep the album after you stop subscribing.

Price type will be: Fixed, Unknown, Name a Price, Subscription.

**Comment by xian2xian2** [comment]
(Sorry for my poor English)

In fact that system just works like Apple Music:
You must have a subscription then you can download a DRM copy for offline listening.
That RMB 2.8 is the price of the subscription, not the album.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/12865009/151603580-bea1e758-e0cc-474f-be05-3144fa571fd5.png">
(Payment page of NetEase Cloud Music)
Music pack = license just for listening and downloading paid songs.
Well, most of new songs are paid now.

There are 3 types of albums on these sites: (like music.163com or y.qq.com )
* Free to listen and download (DRM-free)
* Sub to download (DRM) (like Apple Music)
* Pay to listen and download (DRM-free) (like iTunes Store)

(*2-3) Could be free to listen for the whole song or a little part.

**Comment by Kenneth-T-Moore** [comment]
@xian2xian2  : Thanks for the explanation. I will close this issue. It sounds like these are just like other streaming services, which currently we don't catalog on VGMdb.
