### ISSUE TITLE
How can I receive new album feeds of an artist?

### ISSUE THREAD

**Issue by Yesterday17** [vgmdb/tracker#479]
I used `https://vgmdb.net/artist/${artist_id}/feed` to subscribe for new albums of an artist, but it was removed last month. I found [this](https://vgmdb.net/forums/showthread.php?t=4095&page=4) in changelog:

> Removed legacy album/artist history RSS feeds.

So how can I receive such updates now? Or I have to crawl the webpage and use selectors to extract those information manually?

**Comment by vgmcal** [comment]
The code for RSS feeds had been unmaintained for a long time and was causing issues with the database. At this time we don't have any plans to offer a replacement. Nowadays there are many free services that allow you to create a customized feed of any webpage, so I would recommend trying one of those.
