### ISSUE TITLE
wishlist action "Remove and Add to Collection" doesn't work for multiple albums

### ISSUE THREAD

**Issue by ShiolaElkhart** [vgmdb/tracker#490]
If you try and do this to two albums in your wishlist at once, both will get deleted but only one will be added to your collection

**Comment by Illidanz** [comment]
Just tried this but I can't reproduce it, both albums get removed from the wishlist and are added to the collection. The button basically just redirects to the Add page with the album IDs in the URL, so it should work unless you edit the textbox in the new page.

If you still have the issue let me know what browser you're using and what albums you tried this with.
