### ISSUE TITLE
Song Artists need draft support.

### ISSUE THREAD

**Issue by NicolaasHamman** [vgmdb/tracker#499]
Song Artists credits can't be copied to draft and drafts can be applied to Song Artists pages.

This can lead to a credits lock : I've applied a draft to a release that's marked musically equivalent except songs, but now can't remove the draft because it's applied to BGM and I can't access BGM credits.
https://vgmdb.net/release/15794

**Comment by nstz0** [comment]
While this is an issue that needs to be fixed, there's nothing preventing you from accessing the BGM credits. It's only the menu option that is removed, you can still access the page via it's direct URL (https://vgmdb.net/db/artists-assign.php?releaseid=15794). Or alternatively by temporarily removing the musically equivalent designation.

**Comment by Illidanz** [comment]
Copy to Draft for releases works, you just need to remember to click the "Go to Song Credits" link to see them. This is not very user-friendly but it should be fine since it's for trusted+ only.
