### ISSUE TITLE
Persons that are moved to a unit page still display gender informations

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#500]
![image](https://user-images.githubusercontent.com/53372693/157995398-86c3a16b-11c8-4331-a66a-5dbf50ad82bc.png)
Example: https://vgmdb.net/artist/12003

**Comment by nstz0** [comment]
This also applies to the Education field. The Blood Type field is not displayed on units even if it is filled in. Gender and Education should be updated to match this behavior.

Related issue #344
