### ISSUE TITLE
Unable to link artists or modify role order

### ISSUE THREAD

**Issue by flameshot233** [vgmdb/tracker#510]
https://vgmdb.net/album/91417

I found myself cannot link artists or modify role order after I mass added some artists (those under Staff Comment).
I also found that:
1. Any modification on the artist assign page (and on the draft copied from it) cannot be saved
2. Some artists can be linked by the suggest link page, while others cannot (https://vgmdb.net/db/artists-submit.php?do=suggest&id=37058)

**Comment by Illidanz** [comment]
The album hit a POST limit on the webserver, bumped it up so it should work now.
