### ISSUE TITLE
List the artists of the tracks in tabular form

### ISSUE THREAD

**Issue by tglsf** [vgmdb/tracker#513]
Hello. (Sorry, my English is very poor, so I used a machine translation.)

As the title suggests, music for animation, games, etc. in Japan is often a collaborative effort by very many artists. Composers, lyricists, and arrangers too. Each song may have a different artist.
These artist information is always filled in the "Notes" in VGMdb with romanization.
I am not from Japan, but I am often in contact with the East Asian cultural sphere. I would like these texts to be displayed in their original titles and in the table like the Tracklist, like MusicBrainz. This would make it easier for users who often fill in metadata for local music files (Ctrl and left mouse button drag and copy). I think it would also make it easier to do automatic metadata filling, with artist information accurate to each song, rather than all artists for the entire album.
My ideal style would look like this.

|Track Number|Title|Artist|Composer|Arranger|Lyricist|
|---|---|---|---|---|---|
|01|Music1|Team name [Character 1 (voice actor 1), Character 2 (voice actor 2)]|Composer|Arranger|Lyricist|
|02|Music2|Character 3 (voice actor 3); Character 4 (voice actor 4)|Composer|Arranger|Lyricist|

Or split it into multiple tables: one table showing track information, and another storing composers, arrangers, etc.

I know this is a lot of work for the person filling in the information (and for the programmer as well), but it could be a non-mandatory solution. If the user is familiar with Japanese (the language in which the music is written), they can choose whether they wish to fill in this information or not.

This is just a suggestion.

I don't know if this post is a duplicate, I can't search for related posts (because I don't speak English) and I apologize if it is.

**Comment by vgmcal** [comment]
Unfortunately this isn't possible with VGMdb's current data structure. It may happen one day (see issue #26) but nothing is in development at this time.
