### ISSUE TITLE
Search broken on mobile Chrome

### ISSUE THREAD

**Issue by lbr5539** [vgmdb/tracker#534]
When acessing the site on mobile Chrome (tested on Android), the Enter button is now a Next button, that leads to the selection box beside the search bar, making it unable to give the Enter command to confirm a search (works normally on other mobile browsers like Firefox)
![Screenshot_20220702-150641_Chrome](https://user-images.githubusercontent.com/57114614/177012052-f541dfd2-39cf-46ed-b2a6-0621ce9ac129.jpg)
![Screenshot_20220702-150648_Chrome](https://user-images.githubusercontent.com/57114614/177012065-13791aa6-dddc-404a-99f6-510bf242219b.jpg)

**Comment by Illidanz** [comment]
Fixed, see https://discord.com/channels/439790483494141954/781494728326905856/992878267344375940
