### ISSUE TITLE
Certain platforms instead list as unspecified in most situations.

### ISSUE THREAD

**Issue by NicolaasHamman** [vgmdb/tracker#576]
Choplifter is a good example. The Apple IIGS, Atari 8-bit and Commodore VIC-20 releases are all listed as unspecified on Orgs pages and under the Parent Release options, while at the top of the product page, their releases show no text.

https://vgmdb.net/product/13083
https://vgmdb.net/org/3404?tab=products

**Comment by Illidanz** [comment]
The platforms were missing the short definition in the database, this should be fixed now.
