### ISSUE TITLE
Allow linking of organizations as "artists"

### ISSUE THREAD

**Issue by nstz0** [vgmdb/tracker#66]
Occasionally, albums may include credits like "Script: SUNRISE" or "Illustration: J.C.STAFF". Ideally, we should be able to link these to the organization entries directly without having to create an "artist" entry for them.

One way this could be done is:
- Add a new option for mass add: "Include organizations in lookup."
- When this option is selected the linking page will be loaded with "&org=1" option in the URL.
- On this version of the linking page organization entries will be included in the artist lookup.
- On the organization pages there could be additional tabs for credits, i.e. "Album Credits" and "Product Credits".

One point of discussion is to what degree this change would involve merging existing company "artist" entries (i.e. https://vgmdb.net/artist/5628 and https://vgmdb.net/org/2518).

**Comment by nstz0** [comment]
Another thing: within the artist linking scheme all organizations should be treated as units (since specific members might need to be credited).

**Comment by Illidanz** [comment]
I think the best way to fit this in the current scheme is just creating an artist entry for organizations.

This can be of a new type and linked to an organization (kind of like how we link aliases to parents), and the credit can transparently link to the organization where you would find a new tab for these credits.
