### ISSUE TITLE
Add "Uncredited" flag for role / artist linking

### ISSUE THREAD

**Issue by jsutan** [vgmdb/tracker#69]
Now that we have a more robust role and artist system, propose a new flag for uncredited artists that will indicate the linked artist and/or role is uncredited on the release. Uncredited is defined as any linked artist or role that is not credited anywhere on or in the associated album, be it physical (inserts, case, etc.) or digital (supplemental digital material like PDFs or digital media tags). 

Recommended use should be for situations in which an artist can be confidently verified as contributing to the release. Some examples:

- Social media posts indicating involvement (common for session musicians)
- Interviews with artists indicating involvement. 
- Direct correspondence with artists with a high confidence level. 
- Other releases (past or future) that may have more detailed credits
- Business or legal documents attributing or de-attributing credits (Like Mamoru Samuragoch)
- Generally accepted and validated leaks that lead to attribution credits (see: Falcom leaks)

Recommend not to be used for things like identification based on artistic attributes such as "sounds like" or similar artistic / composition / melody / harmonic attributes. 

There may be some overlap with the "feat." flag that may need to be more thoroughly worked out.

**Comment by Illidanz** [comment]
Not sure how we could display it on the entry itself, maybe a different color for the artist link, or something else?

**Comment by Fivda** [comment]
A color sounds good. We talked about uncreditted classical composers earlier today, and i think this would be a good feature to display the actual composers names even if they're uncreditted or not properly mentionned, despite the very strong hints (in that case, name of the track & composition, though composition/reprises would remain a shaky argument). As far as I know, light/dark blue are the only used colors for artists fields, so there's plenty of choice to go around this idea. Flexible credits aren't optimal when they can easily be mistreated as 100% confirmed informations from booklets etc, but if there's an easy way to show that they're "outside sources", that leaves the door open for more flexible credits while still remaining accurate and viable. Maybe those additional credits could be toggled off by default, and you could toggle those on manually?

Also, you could probably add this to your list:

- Datamining of sound files that feature a clear determination of the corresponding artist [[Example](https://vgmdb.net/forums/showpost.php?p=89908&postcount=8)]

**Comment by vgmcal** [comment]
The display could be as simple as adding an asterisk (doesn't have to be yellow):
![image](https://user-images.githubusercontent.com/74626685/102833400-96520a80-43b6-11eb-9b30-7fec57cc5c1d.png)
![image](https://user-images.githubusercontent.com/74626685/102833405-9baf5500-43b6-11eb-96ea-515698742eae.png)
