### ISSUE TITLE
Mark Twitter account as NSFW

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#83]
Especially now that we can make artist pages for illustrators, and with the twitter accounts displaying full pictures on artists' individual pages, we're bound to find some NSFW content there. How about a checkbox next to the twitter account in the edit page, like "flag as potentially NSFW" so that the previews/twitter inclusion would be hidden/toggled off by default? (enabling explicit content on the settings would always show them by default)

**Comment by Illidanz** [comment]
Doesn't Twitter censor NSFW images by default, including the embedded timelines in artist pages? I'm not sure this is needed on our part.

**Comment by Fivda** [comment]
On twitter web and mobile, yes. But i don't think the preview blocs (forget how those are called) on external website do that

**Comment by Illidanz** [comment]
Tried it out and it does indeed hide NSFW images and videos in the timeline.
