### ISSUE TITLE
Search album issue

### ISSUE THREAD

**Issue by romanoh** [vgmdb/tracker#86]
If i search for Otonoha Letter COMPLETE SET all is fine, 
![imagem](https://user-images.githubusercontent.com/5342223/102710232-dcb94380-42a8-11eb-9569-a9a73d69f6e1.png)

but if i search for Otonoha Letter COMPLETE SET [Limited Edition] it don't show.
![imagem](https://user-images.githubusercontent.com/5342223/102710224-c9a67380-42a8-11eb-88ea-a75c3c90f36a.png)

**Comment by Illidanz** [comment]
This is technically intentional since "[Limited Edition]" is not part of the album title but just added to it when Limited Edition is selected as Distribution Type.

That being said we never liked how that work so we might change it. I've added a separate issue for it.
