### ISSUE TITLE
Release Information: Seperate fields for Label/Publisher/Distributor/PhonoC/etc

### ISSUE THREAD

**Issue by Fivda** [vgmdb/tracker#93]
Instead of the publisher field, add more fields like Label/Publisher/Distributor left for everyone to be able to edit.

**Comment by Illidanz** [comment]
The field works like the products one where one or multiple roles can be assigned to the organizations, this allows to add or tweak these roles without having to add another field which is much more flexible in the long run.

I have renamed the field to "Organizations" to make it more clear though.
