### ISSUE TITLE
Fix thumbnail size for tall images

### ISSUE THREAD

**Issue by Illidanz** [vgmdb/tracker#96]
See the obi thumbnail here: https://vgmdb.net/album/34682

https://thumb-media.vgm.io/albums/28/34682/34682-ddaed4c5976f.jpg

**Comment by Illidanz** [comment]
Should also set a maximum size for the images in the Recent Scans page: https://i.imgur.com/3jG1okD.png

**Comment by vgmcal** [comment]
The issue is that the image scaler doesn't check the width and height values before resizing. It always resizes to a fixed width.

The function should be changed to check the width/height of the input image. This way it will resize based on the height for tall images.
