### ISSUE TITLE
Add composer to calendar view

### ISSUE THREAD

**Issue by Illidanz** [vgmdb/tracker#97]
With the new roles, the composer field is not filled anymore so nothing is displayed on the calendar albums:
https://cdn.discordapp.com/attachments/739956813117784177/790757989392318464/Capture.PNG

The calendar view should display relevant credits there like Composer and Music. This should also apply to products.

**Comment by Illidanz** [comment]
Also happens with the OpenGraph tags for embed on Discord, that are still showing the composer field.

**Comment by lbr5539** [comment]
I'd suggest two solutions for this:
- The first and more simple is to just tweak the two lines a little (move/resize the texts) to make them fill the boxes better, removing that old feature completely
- The second is to make the links to another role appear in the same place, like I suggested [here](https://discord.com/channels/439790483494141954/440516811721539584/848306575650062356) (Discord link), the first role in each album could be displayed, but this would need each album to be changed to have the most "relevant" role in the first slot
